snowball_hit:
  cooldown: 3
  target_message: "&9%shooter% hit you"
  shooter_message: "&9You hit %target%"
  golem_message: "&9A snowman hit you"
snowball_freeze:
  cooldown: 3
  target_message: "&9%shooter% froze you"